### ISSUE TITLE
method errors currently not supported

### ISSUE THREAD

**Issue by Rosi2143** [mintoko/fidl2adoc#9]
When adding "error" to the method the script throws an error:

1. adding error to `method testMethod`
```
        error {
            <**
            @description : Description of the error parameter testParameterError.
            **>
            DIVISION BY ZERO
            OVERFLOW
            UNDERFLOW
        }
```
2. resulting error
```
python3 fidl2adoc/fidl2adoc.py -i examples/Test.fidl -o examples/Test2.adoc

Parsing documentation from Franca IDL files: ['examples/Test.fidl']

Generating ASCIIDoc to file: examples/Test2.adoc

Traceback (most recent call last):

  File "/home/micha/git/pyfrancagen/fidl2adoc/fidl2adoc/fidl2adoc.py", line 366, in <module>

    sys.exit(main(sys.argv[1:]))

  File "/home/micha/git/pyfrancagen/fidl2adoc/fidl2adoc/fidl2adoc.py", line 358, in main

    if not process_inputfiles(inputfiles):

  File "/home/micha/git/pyfrancagen/fidl2adoc/fidl2adoc/fidl2adoc.py", line 324, in process_inputfiles

    processor.import_file(fidl_file.strip())

  File "/home/micha/git/pyfrancagen/pyfranca/pyfranca/franca_processor.py", line 421, in import_file

    self.import_package(fspec, package, references)

  File "/home/micha/git/pyfrancagen/pyfranca/pyfranca/franca_processor.py", line 367, in import_package

    self._update_package_references(package)

  File "/home/micha/git/pyfrancagen/pyfranca/pyfranca/franca_processor.py", line 328, in _update_package_references

    self._update_interface_references(

  File "/home/micha/git/pyfrancagen/pyfranca/pyfranca/franca_processor.py", line 285, in _update_interface_references

    self._update_type_references(namespace, name)

  File "/home/micha/git/pyfrancagen/pyfranca/pyfranca/franca_processor.py", line 236, in _update_type_references

    self._update_type_references(name.namespace, arg.type)

AttributeError: 'Enumerator' object has no attribute 'type'

```

**Comment by mintoko** [comment]
Method errors only work with predefined enumerations as of now.

**Comment by mintoko** [comment]
@Rosi2143 The callstack in your comment points to an issue, which was already fixed in pyfranca: #https://github.com/zayfod/pyfranca/commit/9daa0f0724828177c730faeb729d84ed5ed8510b
Are you using an old version?
Nevertheless, the fidl2adoc support for this feature was added with https://github.com/mintoko/fidl2adoc/commit/e05b056f3e3e2173b5793850b6b975ec6c5d6cf2
